all : basic_debugger basic_debugger2


basic_debugger: basic_debugger.c
	gcc basic_debugger.c -o  basic_debugger.o

basic_debugger2: basic_debugger2.c
	gcc basic_debugger2.c -o  basic_debugger2.o


clean:
	rm *.o
